# Generated by Django 5.2 on 2025-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('school_website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Сайт школы')),
                ('school_photo', models.CharField(blank=True, null=True, verbose_name='Ссылка на фото школы')),
                ('social_vk', models.URLField(blank=True, null=True, verbose_name='Ссылка на ВК')),
                ('social_ok', models.URLField(blank=True, null=True, verbose_name='Ссылка на ОК')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
