# Generated by Django 5.2 on 2025-07-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_email",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="school_website",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Сайт школы"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="social_ok",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ссылка на ОК"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="social_vk",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ссылка на ВК"),
        ),
    ]
