# Generated by Django 5.2 on 2025-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_contact_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="school_website",
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name="Сайт школы"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="social_ok",
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name="Ссылка на ОК"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="social_vk",
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name="Ссылка на ВК"),
        ),
    ]
