# Generated by Django 5.2 on 2025-08-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_contact_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "age",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Возраст"),
                ),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="Ссылка на картинку"),
                ),
                ("review", models.TextField(verbose_name="Отзыв")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
