# Generated by Django 5.2 on 2025-09-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privacy_policy",
                    models.FileField(
                        upload_to="documents_privacy/",
                        verbose_name="Политика конфиденциальности",
                    ),
                ),
                (
                    "user_agreement",
                    models.FileField(
                        upload_to="documents_user/",
                        verbose_name="Пользовательское соглашение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Служебные документы",
                "verbose_name_plural": "Служебные документы",
            },
        ),
    ]
