# Generated by Django 5.2 on 2025-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_legaldocuments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.FileField(upload_to="reviews/", verbose_name="Картинка"),
        ),
    ]
