# Generated by Django 5.2 on 2025-07-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "image_path",
                    models.URLField(verbose_name="Ссылка на картинку-заголовок категории"),
                ),
                (
                    "title",
                    models.CharField(max_length=510, verbose_name="Заголовок категории"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_path", models.URLField(verbose_name="Ссылка на файл")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Описание (для внутреннего использования)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.catalog",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файлы",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.CreateModel(
            name="PhotoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.URLField(verbose_name="Ссылка на картинку")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Описание картинки (для внутреннего использования)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.catalog",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.CreateModel(
            name="VideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_path", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=510,
                        null=True,
                        verbose_name="Описание видео (для внутреннего использования)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.catalog",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
        ),
    ]
