# Generated by Django 5.2 on 2025-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentcontent",
            options={
                "verbose_name": "Файловый контент",
                "verbose_name_plural": "Файловый контент",
            },
        ),
        migrations.AlterModelOptions(
            name="photocontent",
            options={
                "verbose_name": "Фотоконтент",
                "verbose_name_plural": "Фотоконтент",
            },
        ),
        migrations.AlterModelOptions(
            name="videocontent",
            options={
                "verbose_name": "Видео-контент",
                "verbose_name_plural": "Видео-контент",
            },
        ),
    ]
