# Generated by Django 5.2 on 2025-07-27 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_documentcontent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videocontent",
            options={
                "verbose_name": "Видеоконтент",
                "verbose_name_plural": "Видеоконтент",
            },
        ),
    ]
