# Generated by Django 5.2 on 2025-09-03 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_expert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentcontent",
            name="document_path",
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now,
                upload_to="documents/",
                verbose_name="Файл",
            ),
            preserve_default=False,
        ),
    ]
