# Generated by Django 5.2 on 2025-09-09 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_remove_documentcontent_document_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photocontent",
            name="image_path",
        ),
        migrations.AddField(
            model_name="photocontent",
            name="image",
            field=models.FileField(
                default=django.utils.timezone.now,
                upload_to="photos/",
                verbose_name="Картинка",
            ),
            preserve_default=False,
        ),
    ]
