# Generated by Django 5.2 on 2025-09-09 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_remove_photocontent_image_path_photocontent_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalog",
            name="image_path",
        ),
        migrations.AddField(
            model_name="catalog",
            name="image",
            field=models.FileField(
                default=django.utils.timezone.now,
                upload_to="catalogs/",
                verbose_name="Картинка категории",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expert",
            name="image",
            field=models.FileField(upload_to="experts/", verbose_name="Картинка"),
        ),
    ]
