# Generated by Django 5.2 on 2025-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_remove_catalog_image_path_catalog_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocontent",
            name="category",
            field=models.CharField(
                choices=[("masterclass", "Мастер-класс")],
                default="masterclass",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="videocontent",
            name="title",
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name="Заголовок"),
        ),
    ]
