# Generated by Django 5.2 on 2025-10-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_videocontent_category_videocontent_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория контента",
                "verbose_name_plural": "Категории контента",
            },
        ),
        migrations.RemoveField(
            model_name="photocontent",
            name="image",
        ),
        migrations.AddField(
            model_name="photocontent",
            name="title",
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="photocontent",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="content.catalog",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="photocontent",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photos",
                to="content.contentcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="videocontent",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="content.contentcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="photos/", verbose_name="Картинка"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.photocontent",
                        verbose_name="Альбом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
    ]
