# Generated by Django 5.2 on 2025-10-25 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_contentcategory_remove_photocontent_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalog",
            options={
                "ordering": ["pk"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="contentcategory",
            options={
                "ordering": ["pk"],
                "verbose_name": "Категория контента",
                "verbose_name_plural": "Категории контента",
            },
        ),
        migrations.AlterModelOptions(
            name="documentcontent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Файловый контент",
                "verbose_name_plural": "Файловый контент",
            },
        ),
        migrations.AlterModelOptions(
            name="expert",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Наставник",
                "verbose_name_plural": "Наставники",
            },
        ),
        migrations.AlterModelOptions(
            name="photocontent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Фотоконтент",
                "verbose_name_plural": "Фотоконтент",
            },
        ),
        migrations.AlterModelOptions(
            name="videocontent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Видеоконтент",
                "verbose_name_plural": "Видеоконтент",
            },
        ),
    ]
