import { Suspense } from 'react';
import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';
import './globals.css';
import Navigation from './components/Navigation/Navigation';
import { PageWidthProvider } from './context/PageWidthProvider'; // Импортируем PageWidthProvider отдельно

export const metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
 return (
  <html lang="ru">
   <body>
    <PageWidthProvider>
     <Suspense fallback={<div>Loading...</div>}>
      <Header />
      <Navigation />
      {children}
      <Footer />
     </Suspense>
    </PageWidthProvider>
   </body>
  </html>
 );
}
