import { Suspense } from 'react';
import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';
import './globals.css';
import Navigation from './components/Navigation/Navigation';
import { PageWidthProvider } from './context/PageWidthProvider';
import { PageTitleProvider } from './context/PageTitleContext';
import { montserrat, comfortaa, inter } from '@/lib/fonts';
import {PopUpProvider} from "@/app/context/PopUpContext";
import PopUpAttribution from "@/app/components/PopUpAttribution/PopUpAttribution";
import {AuthProvider} from "@/app/context/AuthContext";

export const metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
 return (
  <html lang="ru" className={`${montserrat.className} ${comfortaa.className} ${inter.className}`}>
   <body>
   <AuthProvider>
    <PopUpProvider>
     <PopUpAttribution />
     <PageTitleProvider>
      <PageWidthProvider>
       <Suspense fallback={<div>Loading...</div>}>
        <div style={{minHeight: '100vh', display: 'flex', flexDirection: 'column'}}>
         <Header />
         <Navigation />
         <main style={{flex: 1}}>
          {children}
         </main>
         <Footer />
        </div>
       </Suspense>
      </PageWidthProvider>
     </PageTitleProvider>
    </PopUpProvider>
   </AuthProvider>
   </body>
  </html>
 );
}
