import { Suspense } from "react";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import "./globals.css";
import Navigation from "./components/Navigation/Navigation";
import About from "./about/About";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children}) {
  return (
    <html lang="ru">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
          <Navigation />
          {children}
          <About />
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
