# Generated by Django 5.2 on 2025-08-27 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_paragraph_options_alter_announcement_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Анонс",
                "verbose_name_plural": "Анонсы",
            },
        ),
        migrations.AlterModelOptions(
            name="competition",
            options={
                "ordering": ("-created_at", "start_date", "end_date"),
                "verbose_name": "Конкурс",
                "verbose_name_plural": "Конкурсы",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
