# Generated by Django 5.2 on 2025-09-06 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_announcement_options_alter_competition_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Одобрено"),
                ),
                (
                    "question_category",
                    models.CharField(
                        choices=[
                            ("expert", "Вопрос эксперту/преподавателю"),
                            ("technical", "Технический вопрос"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Категория вопроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="paragraph",
            name="news_or_announcement_or_competition",
        ),
        migrations.AddField(
            model_name="answer",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.announcement",
                verbose_name="Анонс",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.competition",
                verbose_name="Конкурс",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="news",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="news.news",
                verbose_name="Новость",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="news.comment",
                verbose_name="Комментарии",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("news__isnull", False),
                        ("announcement__isnull", True),
                        ("competition__isnull", True),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", False),
                        ("competition__isnull", True),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", True),
                        ("competition__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="only_one_news_or_announcement_or_competition_comment",
            ),
        ),
    ]
