# Generated by Django 5.2 on 2025-09-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_answer_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="only_one_news_or_announcement_or_competition_comment",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="image_path",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="image_path",
        ),
        migrations.RemoveField(
            model_name="news",
            name="image_path",
        ),
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="news/", verbose_name="Картинка"),
        ),
        migrations.AddField(
            model_name="competition",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="news/", verbose_name="Картинка"),
        ),
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="news/", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="paragraphs/", verbose_name="Картинка"),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("news__isnull", False),
                        ("announcement__isnull", True),
                        ("competition__isnull", True),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", False),
                        ("competition__isnull", True),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", True),
                        ("competition__isnull", False),
                    ),
                    models.Q(
                        ("news__isnull", False),
                        ("announcement__isnull", False),
                        ("competition__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="only_one_news_or_announcement_or_competition_or_general_comment",
            ),
        ),
    ]
