# Generated by Django 5.2 on 2025-09-30 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "news",
            "0005_remove_comment_only_one_news_or_announcement_or_competition_comment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="only_one_news_or_announcement_or_competition_or_general_comment",
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("news__isnull", False),
                        ("announcement__isnull", True),
                        ("competition__isnull", True),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", False),
                        ("competition__isnull", True),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", True),
                        ("competition__isnull", False),
                    ),
                    models.Q(
                        ("news__isnull", True),
                        ("announcement__isnull", True),
                        ("competition__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="only_one_news_or_announcement_or_competition_or_general_comment",
            ),
        ),
    ]
