# Generated by Django 5.2 on 2025-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post",
            field=models.CharField(
                blank=True,
                help_text="Не более 50 символов.",
                max_length=70,
                null=True,
                verbose_name="Должность",
            ),
        ),
    ]
